[package]
name = "whale-flow-pro"
version = "0.4.2"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["rustls", "legacy"] }
tokio = { version = "1.0", features = ["full"] }
arkworks-crypto = { git = "https://github.com/arkworks-rs/crypto", rev = "v0.3.0" }
