name: Security Audit
on: [push]

jobs:
  halborn-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: halborn/action@v2
        with:
          api-key: ${{ secrets.HALBORN_KEY }}
          critical-threshold: 0
